---
output: html_document
pagetitle: Home
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r eventlist, include=FALSE}
list_of_events<- list("AHAHTN2020", "ASNC2020", "SCCT2020", "SNMMI2020",  "SVM2020", "AHAVD2020", "SCCTInnovation2020", "SCMR2020", "MITNYC2019", "MITURTC2019", "AIMED18")
```


<!--Banner content-->
```{ =html}
<style>
.main-container{
  padding-left: 0;
  padding-right:0;
  max-width: 100%;
}

.banner{
        position: relative;
        display: table;
        width: 100%;
        height: 30vh;
        margin-bottom: 5rem;
        text-align: center;
        background: url(images/triangle.png) no-repeat center center;
        background-size: cover;
        overflow: hidden;
        margin-top: 0px; 
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.1);
}

.banner-content{
 padding: 75px 0;
}

.button{
  background-color: transparent;
  color: white;
  border: 2px solid #FFFFFF; /* Green */
  border-radius: 10px;
  height: 45px;
}

.link { color: #FFFFFF; }
h1 {color: #FFFFFF;}
i {color: #FFFFFF;}

</style>

<div class="banner">
  <div class="banner-content">
    <h1>Abhi Bhattaru</h1>
    <i>"You miss 100% of the shots you don't take." -Wayne Gretzky -Micheal Scott</i>
    <br><br>
    <button type="button" class="button"><a class="link" href="about.html"><b>About</b></a></button>
    <button type="button" class="button"><a class="link" href="research.html"><b>Research Gallery</b></a></button>
    <button type="button" class="button"><a class="link" href="listed_works.html"><b>Listed Works</b></a></button>
  </div>
</div>

```


<!--Main Content-->
```{=html}
<style>
p{
  max-width: 960px;
  margin-left: auto;
  margin-right: auto;
  font-size: 15px;
  margin-bottom: .05em;
}
h2{
  font-weight: 500;
  max-width: 960px;
  margin-left: auto;
  margin-right: auto;
}
h3{
  font-weight: 500;
  max-width: 960px;
  margin-left: auto;
  margin-right: auto;
}
hr{
  border: .5px solid gray;
  max-width: 960px;
  margin-left: auto;
  margin-right: auto;
}
.row{
  max-width: 960px;
  margin-left: auto;
  margin-right: auto;
}
</style>
```

<h2>Events</h2>
<hr>

``` {r testingsomething, echo=FALSE}
library(shiny)
string_files<-''
rendered_elements<- for (i in list_of_events){
  yaml<- rmarkdown::yaml_front_matter(paste("Events/",i,'/',i,'.Rmd',  sep=''))
  string_files<-paste(string_files, 
                      fluidRow(
                        column(3,
                               img(src=paste("Events/",i,'/', yaml$img_name,  sep='')),
                               br(),
                               p(yaml$date),
                               br()
                               ),
                        column(9,
                               a(HTML('<h4>',paste(yaml$pagetitle),'</h4>'), href=paste("Events/",i,'/',i,'.html',  sep='')),
                               p(yaml$description)
                               )
                        ),
                      hr()
                      )
}
```
```{=html}
`r string_files`
```



<!---
```{r testingfunctions, echo=FALSE, include=FALSE}
library(shiny)
textthing<- paste(rmarkdown::yaml_front_matter("papers/Endocarditis/Endocarditis.Rmd")$author[1], rmarkdown::yaml_front_matter("papers/Endocarditis/Endocarditis.Rmd")$author[2])

out<- knitr::knit(text = textthing)

```
--->




<br>

