---
output: html_document
pagetitle: Listed Works
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{=html}
<style>
p{
  font-size: 15px;
  margin-bottom: .05em;
}
h2{
font-weight: 500;
}
h3{
font-weight: 500;
}
h4{
font-weight: 500;
}
hr{
border: 1px solid gray;
}
title{
display: none;
}
</style>
```


<h2>Listed Works</h2>
```{r papers, tidy=TRUE, echo=FALSE}
library(shiny)

tabsetPanel(

tabPanel( "Manuscripts",
br(),
h4('Manuscripts'),
hr(),
em('Published'),
HTML('
  <ol>
    <li>S Patil, C Rojulpote, K Gonuguntla, P Karambelkar, <b>A Bhattaru</b>, WY Raynor, AJ Borja, K Vuthaluru, V Zhang, TJ Werner, O Gerke, PF Høilund-Carlsen, A Alavi. Association of Triglyceride to High Density Lipoprotein Ratio with Global Cardiac Microcalcification in Healthy Non-diabetic Individuals as Assessed by NaF-PET/CT to Evaluate Subclinical Coronary Atherosclerosis. <em>American Journal of Cardiovascular Disease.</em> August 15, 2020.</li>
    <li> K Gonuguntla, S Patil, C Rojulpote , RG Cowden, M Nasir, P Karambelkar, T Buch, A Aujla, <b>A Bhattaru</b>, ZE Borja, P Schulman. A Population Based Analysis of Trends, Risk Factors And Outcomes Associated With Gastrointestinal Bleeding In Patients With Left Ventricular Assist Devices. <em>American Journal of Cardiovascular Disease.</em> August 15, 2020.</li>
    <li>V Zhang, B Koa, AJ Borja, S Padmanhabhan, <b>A Bhattaru</b>, WY Raynor, C Rojulpote, SM Seraj, TJ Werner, C Rajapakse, A Alavi, ME Revheim. Diagnosis and Monitoring of Osteoporosis with Total-Body 18F-Sodium Fluoride Positron Emission Tomography/Computed Tomography. <em>PET Clinics.</em> August 4th, 2020. </li>
    <li>C Rojulpote, S Patil, K Gonuguntla, PE Bravo, SM Seraj, S Asadollahi, WY Raynor, <b>A Bhattaru</b>, P Karambelkar, AJ Borja, V Zhang, TJ Werner, O Gerke, PF Hoilund-Carlsen, A Alavi. NaF-PET/CT global assessment in detecting and quantifying subclinical cardiac atherosclerosis and its association with blood pressure in non-dyslipidemic individuals. <em>American Journal of Cardiovascular Disease.</em> June 15, 2020. </li>
    <li>C Rojulpote, K Gonuguntla, S Patil, <b>A Bhattaru</b>, PE Bravo. COVID-19 and the Heart. <em>Colombia Médica.</em> June 3, 2020.</li>
    <li>K Gonuguntla, S Patil, RG Cowden, M Kumar, C Rojulpote, <b>A Bhattaru</b>, JG Tiu, P Robinson. Predictors of in-hospital mortality in patients with left ventricular assist device. <em>Irish Journal of Medical Science.</em> May 9, 2020.</li>
    <li>P Karambelkar, C Rojulpote, AJ Borja, A Youngs, <b>A Bhattaru</b>. An Unusual Case of Tricuspid Valve Infective Endocarditis Caused by Erysipelothrix Rhusiopathiae. <em>Cureus</em>. May 9, 2020.</li>
    <li>S Durugu, K Gonuguntla, S Patil, C Rojulpote, V Vyata, P Karambelkar, P Narayanareddy, K Vuthaluru, <b>A Bhattaru</b>. Gender Differences in Rates of Arrhythmias, Cardiac Implantable Electronic Devices, and Diagnostic Modalities Among Sarcoidosis Patients. <em>Cureus.</em> April 14, 2020</li>
    <li>K Gonuguntla, S Patil, NV Gadela, RC Cowden, C Rojulpote, S Durugu, P Karambelkar, <b>A Bhattaru</b>, AJ Borja, V Zhang. Trends, Outcomes, and Predictors of Sepsis and Severe Sepsis in Patients with Left Ventricular Assist Devices. <em>Cureus.</em> April 3, 2020.</li>
    <li>C Rojulpote, A Matthew, MK Yarlagadda, <b>A Bhattaru</b>, K Vuthaluru. Conned by Conn’s: The Manifestation of Conn’s Syndrome Post-renal Transplant in a Patient with Polycystic Kidney Disease. <em>Cureus</em>. April 2, 2020. </li>
  </ol>
     '),
em('In Press'),
HTML('
  <ol>
    <li>AJ Borja, <b>A Bhattaru</b>, C Rojulpote, EC Hancin, DK Detchou, S Patil, K Gonuguntla, P Karambelkar, S Chinta, K Vuthaluru, TJ Werner, O Gerke, PF Høilund-Carlsen, Abass Alavi. Association between Atherosclerotic Cardiovascular Disease Risk Score Estimated by Pooled Cohort Equation and Coronary Plaque Burden as Assessed by NaF-PET/CT. <em>American Journal of Nuclear Medicine and Molecular Imaging</em></li>
    <li>K Gonuguntla, C Rojulpote, S Patil, <b>A Bhattaru</b>, P Karambelkar, K Vuthaluru, WY Raynor, AJ Borja, V Zhang, TJ Werner, O Gerke, PF Høilund-Carlsen, A Alavi. Utilization of NaF-PET/CT in Assessing Global Cardiovascular Calcification Using CHADS2 and CHADS2-VASc Scoring Systems in High Risk Individuals for Cardiovascular Disease. <em>American Journal of Nuclear Medicine and Molecular Imaging</em></li>
  
    <li><b>A Bhattaru</b>, N Deshmukh, S Makkapati, N Nakamitsu. Detecting Organ Failure in Motor Vehicle Trauma Patients: A Machine Learning Approach. <em>2019 IEEE MIT Undergraduate Research Technology Conference (URTC)</em>
</li>
  </ol>
     '),
br()

),





tabPanel("Abstracts",
br(),
h4('Abstracts'),
hr(),
em('Oral Presentations'),
HTML('
 <ol>
    <li><b>A Bhattaru</b>, C Rojulpote, R Ghorpade, PE Bravo, S Patil, K Gonuguntla, P Karambelkar, K Vuthaluru, V Zhang, TJ Werner, A Alavi. Correlation Between Blood Pressure And Inflammation In The Thoracic Aorta Of HIV Patients With And Without Cocaine Use As Assessed By FDG-PET/CT. <em>Hypertension</em>. September 9th, 2020. Presented at: American Heart Association Hypertension 2020.</li>
    <li><b>A Bhattaru</b>, A Tandon, R Davies, D Sutcliffe, R Butts, J Dillenbeck, G Greil, T Hussain. Role of Computed Tomography in Pediatric Ventricular Assist Device Fitting. <em>Journal of Cardiovascular Computed Tomography.</em> July 17, 2020. Presented at: Society of Cardiovascular Computed Tomography 2020. </li>
    <li><b>A Bhattaru</b>, V Gooty, J Dillenbeck, T Hussain. Practical Challenges of Machine Learning on the diagnosis of Cardiac Allograft Vasculopathy using Computed Tomography in pediatrics. Presented at: SCCT Innovation 2020.</li>
    <li><b>A Bhattaru</b>, N Deshmukh, S Makkapati, N Nakamitsu. Detecting Organ Failure in Motor Vehicle Trauma Patients: A Machine Learning Approach. Presented at: MIT Undergraduate Research and Technology Conference 2019, AIMed 2018. </li>
 </ol>
'),
em('Poster Presentations'),
HTML('
  <ol>
     <li><b>A Bhattaru</b>, R Ghorpade, C Rojulpote, PE Bravo, S Patil, K Gonuguntla, P Karambelkar, K Vuthaluru, V Zhang, TJ Werner, A Alavi. Correlation Between Blood Pressure And Left Ventricular Metabolism In HIV Individuals With And Without Cocaine Use As Assessed By FDG-PET/CT. <em>Hypertension</em>. September 9th, 2020. Presented at: American Heart Association Hypertension 2020.</li>
    <li>C Rojulpote, S Patil, K Gonuguntla, PE Bravo, P Karambelkar, <b>A Bhattaru</b>, V Zhang, T Werner, O Gerke, P Hoilund-Carlsen, A Alavi. Association of Atherosclerotic Cardiovascular Risk Estimated by Pooled Cohort Equation With Coronary Plaque Burden as Assessed by NaF-PET/CT. <em>Arteriosclerosis, Thrombosis, and Vascular Biology.</em> June 29, 2020.  Presented at: AHA Vascular Discovery 2020. </li>
    <li>C Rojulpote, S Patil, K Gonuguntla, P Karambelkar, <b>A Bhattaru</b>, S Asadollahi, T Werner, P Hoilund-Carlsen, A Alavi. Comparison of atherosclerotic burden in non- lower extremity vasculature in patients with and without peripheral artery disease using 18F- sodium fluoride imaging. <em>Vascular Medicine.</em> May 22, 2020. Presented at: Society of Vascular Medicine 2020.
</li>
    <li><b>A Bhattaru</b>, A Borja, V Zhang, KV Rojulpote, T Werner, A Alavi, ME Revheim. FDG-PET/CT as the superior imaging modality for inflammatory bowel disease. <em>Journal of Nuclear Medicine.</em> May 1, 2020. Presented at: Society of Nuclear Medicine and Molecular Imaging 2020.
</li>
    <li><b>A Bhattaru</b>, V Zhang, E Hancin, A Borja, KV Rojulpote, T Werner, ME Revheim, A Alavi. Potential applications of FDG-PET/MRI in detecting vascular dementia. <em>Journal of Nuclear Medicine.</em> May 1, 2020. Presented at: Society of Nuclear Medicine and Molecular Imaging 2020.
</li>
    <li>C Rojulpote, <b>A Bhattaru</b>, S Patil, K Gonuguntla, ME Revheim, B Koa, E Hancin, T Werner, A Alavi. Role of PET Imaging in Detection and Management of Arrhythmias. <em>Journal of Nuclear Medicine.</em> May 1, 2020. Presented at: Society of Nuclear Medicine and Molecular Imaging 2020.
</li>
    <li>V Zhang, <b>A Bhattaru</b>, C Rojulpote, A Borja, A Madiraju, T Werner, A Alavi, ME Revheim. Role of PET/CT Imaging in the Assessment of Pulmonary Artery Atherosclerosis. <em>Journal of Nuclear Medicine.</em> May 1, 2020. Presented at: Society of Nuclear Medicine and Molecular Imaging 2020.
</li>
    <li>E Hancin, A Borja, <b>A Bhattaru</b>, SM Seraj, KV Rojulpote, T Werner, A Alavi, ME Revheim. Applications of FDG-PET/CT and NaF-PET/CT in the Surgical Management of Musculoskeletal Infection. <em>Journal of Nuclear Medicine.</em> May 1, 2020. Presented at: Society of Nuclear Medicine and Molecular Imaging 2020.
</li>
    <li>V Zhang, C Rojulpote, AJ Borja, A Madiraju, <b>A Bhattaru</b>, S Patil, K Gonuguntla, TJ Werner, PF Hoilund-Carlsen, ME Revheim, A Alavi. NaF Uptake in the Pulmonary Artery Stratified by Systemic Blood Pressure: A Novel Methodology. <em>Journal of Nuclear Medicine.</em> May 1, 2020. Presented at: Society of Nuclear Medicine and Molecular Imaging 2020.
</li>
    <li>S Patil, K Gonuguntla, C Rojulpote, V Zhang, B Koa, <b>A Bhattaru</b>, ME Revheim, T Werner, A Alavi. Role of PET Imaging in Aortic Stenosis. <em>Journal of Nuclear Medicine.</em> May 1, 2020. Presented at: Society of Nuclear Medicine and Molecular Imaging 2020.
</li>
    <li>V Zhang, S Padmanabhan, B Koa, A Borja, WY Raynor, A Madiraju, <b>A Bhattaru</b>, KV Rojulpote, C Rajapakse, T Werner, ME Revheim, A Alavi. Total-Body NaF-PET/CT and its Implications for Osteoporosis. <em>Journal of Nuclear Medicine.</em> May 1, 2020. Presented at: Society of Nuclear Medicine and Molecular Imaging 2020.
</li>
    <li>C Rojulpote, S Patil, K Gonuguntla, ME Revheim, R Ghorpade, P Narayanareddy, <b>A Bhattaru</b>, TJ Werner, O Gerke, PF Hoilund-Carlsen, A Alavi. Role of NaF-PET/CT in Detecting and Quantifying Global Cardiac Subclinical Atherosclerosis in Healthy Individuals with an Optimal Lipid Profile and its Association with Blood Pressure. <em>Journal of Nuclear Medicine.</em> May 1, 2020. Presented at: Society of Nuclear Medicine and Molecular Imaging 2020.
</li>
    <li>DA Castellanos, K Škardová, <b>A Bhattaru</b>, G Greil, A Tandon, J Dillenbeck, B Burkhardt, T Hussain, M Genet, R Chabiniok. Left ventricular torsion obtained using equilibrated warping in patients with repaired Tetralogy of Fallot. Presented at: Society for Cardiovascular Magnetic Resonance 2020.
</li>
  </ol>
'),
em("Accepted"),
HTML('
  <ol>
    <li><b>A Bhattaru</b>, WY Raynor, S Patil, C Rojulpote, PE Bravo, K Gonuguntla, P Karambelkar, K Vuthaluru, SM Seraj, V Zhang, T Werner, JF Baker, A Alavi. Association Of Serum Leptin And Abdominal Aortic Inflammation In Rheumatoid Arthritis. <em>Arteriosclerosis, Thrombosis and Vascular Biology</em>. Presented at: American Heart Association Sessions 2020.</li>
    <li>C Rojulpote, <b>A Bhattaru</b>, K Gonuguntla, S Patil, P Karambelkar, T Buch, K Vuthaluru, S Shrivastava, N Perosevic. Pacemaker In The Elderly: A Nationwide Cohort To Determine Complications Associated With Pacemakers. <em>CLCD</em>. Presented at: American Heart Association Sessions 2020.</li>
    <li>C Rojulpote, K Gonuguntla, S Patil, P Karambelkar, T Buch, <b>A Bhattaru</b>, K Vuthaluru, N Perosevic, PE Bravo. Gender Differences Amongst Caucasians And African Americans In Rates Of Arrhythmias, Implantable Cardiac Devices, And In-hospital Mortality In Sarcoidosis Patients With Cardiomyopathy <em>EPI</em>. Presented at: American Heart Association Sessions 2020.</li>
    <li>V Zhang, C Rojulpote, AJ Borja, A Madiraju, <b>A Bhattaru</b>, K Gonuguntla, S Patil, TJ Werner, A Alavi, ME Revheim. Correlation between age and pulmonary artery calcification: a novel finding assessed by 18F NaF-PET/CT. <em>CHEST</em>. Presented at: CHEST annual meeting 2020.</li>
    <li>CS Rojulpote, K Gonuguntla, S Patil, P Karambelkar, A Gade, <b>A Bhattaru</b>. Predictors of in-hospital mortality in Sarcoidosis patients with cardiomyopathy. <em>CHEST</em>. Presented at: CHEST annual meeting 2020.</li>
    <li>CS Rojulpote, S Patil, K Gonuguntla, P Karambelkar, ZE Borja, M Kumar, V Zhang, <b>A Bhattaru</b>, A Gade. A nation wide cohort analysis of pneumococcal vaccination and prevalence of in-hospital mortality in acute coronary syndrome. <em>CHEST</em>. Presented at: CHEST annual meeting 2020.</li>
    <li>K Gonuguntla, C Rojulpote, S Patil, P Karambelkar, <b>A Bhattaru</b>, K Vuthaluru, TJ Werner, PF Hoilund-Carlsen, A Alavi. Atherosclerotic Cardiovascular Disease Risk Estimated by Pooled Cohort Equation Predicts Global Cardiac Microcalcification in Patients with Angina. <em>Journal of Nuclear Cardiology</em>. Presented at: American Society of Nuclear Cardiology 2020 meeting.</li>
    <li>K Gonuguntla, C Rojulpote, S Patil, P Karambelkar, K Vuthaluru, <b>A Bhattaru</b>, V Zhang, TJ Werner, PF Hoilund-Carlsen, A Alavi. Presence of Coronary Molecular Calcification and its Correlation to Calcification Processes in Upper Limb, Abdominal and Lower Extremity Arteries as Assessed by NaF-PET/CT. <em>Journal of Nuclear Cardiology</em>. Presented at: American Society of Nuclear Cardiology 2020 meeting.</li>
    <li>K Gonuguntla, C Rojulpote, S Patil, P Karambelkar, K Vuthaluru, <b>A Bhattaru</b>, V Zhang, TJ Werner, PF Hoilund-Carlsen, A Alavi. Utility of NaF-PET/CT in Assessing Subclinical Atherosclerosis in Peripheral Arteries of Healthy Individuals with an Optimal Cardiovascular Risk Factor Profile. <em>Journal of Nuclear Cardiology</em>. Presented at: American Society of Nuclear Cardiology 2020 meeting.</li>
    
  </ol>
')
)


)
```
<br>















