---
pagetitle: "American Heart Association Vascular Discovery From Genes to Medicine Scientific Sessions 2020"
author: "Abhi Bhattaru"
date: "May 5-7, 2020"
img_name: "vascularlogo.png"
description: "The virtual event will provide an exchange of information about new and emerging scientific research in the areas of arteriosclerosis, thrombosis, vascular biology, genomics, precision medicine, peripheral vascular disease, and vascular surgery to a broad audience from many disciplines. This event is for scientists and clinicians in cardiovascular medicine, cardiovascular research, thrombosis research, clinical cardiology, molecular/cellular biology, vascular biology, vascular medicine, vascular surgery, endocrinology, genetics, functional genomics, hematology, immunology and physiology. View published poster"
output: 
  html_document:
    theme: sandstone
    include:
      in_header: header.html
      after_body: footer.html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{=html}
<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="../../index.html">Abhi Bhattaru</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="../../index.html">Home</a>
</li>
<li>
  <a href="../../about.html">About</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Research
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="../../research.html">Paper Gallery</a>
    </li>
    <li>
      <a href="../../listed_works.html">Listed Works</a>
    </li>
  </ul>
</li>
<li>
  <a href="../../shiny.html">Applications</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://www.linkedin.com/in/abhijit-bhattaru-3693a9177">
    <span class="fa fa-linkedin fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="https://scholar.google.com/citations?view_op=list_works&amp;hl=en&amp;authuser=1&amp;user=WJHf9fsAAAAJ">
    <span class="fa fa-graduation-cap fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="https://www.researchgate.net/profile/Abhi_Bhattaru">
    <span class="fa fa fa fa-university fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="https://github.com/abhimaster2001">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="mailto:abhi.bhattaru@gmail.com">
    <span class="fa fa-envelope fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<style>
p{
  font-size: 15px;
  margin-bottom: .05em;
}
h2{
font-weight: 500;
}
h3{
font-weight: 500;
}
h4{
font-weight: 500;
}
hr{
border: 1px solid gray;
}
title{
display: none;
}
</style>

```


<br> <br> <br>

```{r webdisplay, echo=FALSE}
library(shiny)
yaml_info<- rmarkdown::yaml_front_matter('AHAVD2020.Rmd')

HTML('<h2>', yaml_info$pagetitle, '</h2>' , '<hr>')

fluidRow(
    column(4,
      img(src=yaml_info$img_name),
      br(),
      p(yaml_info$date),
      br()
          ),
    column(8,
      HTML("</p>", yaml_info$description, "</p>"),
      br()
          )
)
br()
HTML('<h4>', 'Poster Presentation', '</h4>' , '<hr>')
HTML('
 <ol>
    <li>C Rojulpote, S Patil, K Gonuguntla, PE Bravo, P Karambelkar, <b>A Bhattaru</b>, V Zhang, T Werner, O Gerke, P Hoilund-Carlsen, A Alavi. Association of Atherosclerotic Cardiovascular Risk Estimated by Pooled Cohort Equation With Coronary Plaque Burden as Assessed by NaF-PET/CT. <a href="https://www.ahajournals.org/doi/10.1161/atvb.40.suppl_1.274">Arteriosclerosis, Thrombosis, and Vascular Biology. June 29, 2020.</a></li>
 </ol>
')

br()
```