---
pagetitle: "American Heart Association Scientific Sessions 2020"
author: "Abhi Bhattaru"
date: "November 13–17, 2020"
img_name: "AHASESS2020.png"
description: "The meeting will focus on recent advances in cardiovascular illnesses, from hypertension to atherosclerosis. This is the largest yearly AHA conference with esteemed professionals from around the world showcasing their work. View poster presentations."
output: 
  html_document:
    theme: sandstone
    include:
      in_header: header.html
      after_body: footer.html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{=html}
<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="../../index.html">Abhi Bhattaru</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="../../index.html">Home</a>
</li>
<li>
  <a href="../../about.html">About</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Research
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="../../research.html">Paper Gallery</a>
    </li>
    <li>
      <a href="../../listed_works.html">Listed Works</a>
    </li>
  </ul>
</li>
<li>
  <a href="../../shiny.html">Applications</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://www.linkedin.com/in/abhijit-bhattaru-3693a9177">
    <span class="fa fa-linkedin fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="https://scholar.google.com/citations?view_op=list_works&amp;hl=en&amp;authuser=1&amp;user=WJHf9fsAAAAJ">
    <span class="fa fa-graduation-cap fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="https://www.researchgate.net/profile/Abhi_Bhattaru">
    <span class="fa fa fa fa-university fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="https://github.com/abhimaster2001">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="mailto:abhi.bhattaru@gmail.com">
    <span class="fa fa-envelope fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<style>
p{
  font-size: 15px;
  margin-bottom: .05em;
}
h2{
font-weight: 500;
}
h3{
font-weight: 500;
}
h4{
font-weight: 500;
}
hr{
border: 1px solid gray;
}
title{
display: none;
}

.paper-listing {
  position: relative;
  overflow: hidden;
}

.paper-listing:hover .paper-title {
  opacity: 1;
}

.paper-listing:hover .paper-image img {
  filter: blur(2px);
}

.paper-image img {
  filter: blur(0px);
  transition: filter 0.3s ease-in;
  transform: scale(1.1);
}

.paper-title {
  position: absolute;
  top: 0;
  left: 0;
  height: 100%;
  width: 100%;
  background: rgb(179, 0, 71);
   
  /* typographic styles */
  color: white;
  font-size: 1.5em;
  font-weight: bold;
  text-decoration: none;
   
  /* position the text centrally*/
  display: flex;
  align-items: center;
  justify-content: center;
  
  /* hide the title by default */
  opacity: 0;
  transition: opacity .5s;
  
  z-index: 1;
}

img {
  width: 100%;
  height: auto;
}

@media (hover: none) { 
  .paper-title {
    opacity: 1;
    background: none;
  }
  .paper-image img {
    filter: blur(0px);
  }
}

</style>

```


<br> <br> <br>

```{r webdisplay, echo=FALSE}
library(shiny)
yaml_info<- rmarkdown::yaml_front_matter('AHASESS2020.Rmd')

HTML('<h2>', yaml_info$pagetitle, '</h2>' , '<hr>')

fluidRow(
    column(4,
      img(src=yaml_info$img_name),
      br(),
      p(yaml_info$date),
      br()
          ),
    column(8,
      HTML("</p>", yaml_info$description, "</p>"),
      br()
          )
)
br()
HTML('<h4>', 'Poster Presentation', '</h4>' , '<hr>')
fluidRow()
HTML('
 <ol>
     <li><b>A Bhattaru</b>, WY Raynor, S Patil, C Rojulpote, PE Bravo, K Gonuguntla, P Karambelkar, K Vuthaluru, SM Seraj, V Zhang, T Werner, JF Baker, A Alavi. Association of Serum Leptin and Abdominal Aortic Inflammation in Rheumatoid Arthritis. <a href = "https://doi.org/10.1161/circ.142.suppl_3.14521"><em>Circulation</em>. November 12th, 2020.</a></li>
     <li>C Rojulpote, <b>A Bhattaru</b>, K Gonuguntla, S Patil, P Karambelkar, T Buch, K Vuthaluru, S Shrivastava, N Perosevic. Pacemaker in the Elderly: A Nationwide Cohort to Determine Complications Associated With Pacemakers. <a href = "https://www.ahajournals.org/doi/abs/10.1161/circ.142.suppl_3.16159"><em>Circulation</em>. November 12th, 2020.</a></li>
     <li>C Rojulpote, K Gonuguntla, S Patil, P Karambelkar, T Buch, <b>A Bhattaru</b>, K Vuthaluru, N Perosevic, PE Bravo. Gender Differences Amongst Caucasians and African Americans in Rates of Arrhythmias, Implantable Cardiac Devices, and In-hospital Mortality in Sarcoidosis Patients With Cardiomyopathy. <a href = "https://doi.org/10.1161/circ.142.suppl_3.15038"><em>Circulation</em>. November 12th, 2020.</a></li>
 </ol>
')

br()
```